apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
        - name: crm-service
          image: 502612814580.dkr.ecr.us-east-1.amazonaws.com/crm-service:latest
          imagePullPolicy: Always
          env:
            - name: ANDREW_ID
              value: "irish2"
            - name: KAFKA_BROKERS
              value: "REPLACE_ME_KAFKA_BROKER_1:9092"
            - name: KAFKA_TOPIC
              value: "irish2.customer.evt"
            - name: KAFKA_CLIENT_ID
              value: "crm-service"
            - name: KAFKA_GROUP_ID
              value: "crm-service-group"
            - name: SMTP_HOST
              value: "REPLACE_ME_SMTP_HOST"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              value: "REPLACE_ME_SMTP_USER"
            - name: SMTP_PASS
              value: "REPLACE_ME_SMTP_PASS"
            - name: EMAIL_FROM
              value: "irish2@andrew.cmu.edu"
