apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
        - name: crm-service
          image: crm-service:latest
          imagePullPolicy: Always
          env:
            - name: ANDREW_ID
              value: "<andrew_id>"
            - name: KAFKA_BROKERS
              value: "<broker-1:9092,broker-2:9092>"
            - name: KAFKA_TOPIC
              value: ""
            - name: KAFKA_CLIENT_ID
              value: "crm-service"
            - name: KAFKA_GROUP_ID
              value: "crm-service-group"
            - name: SMTP_HOST
              value: "<smtp-host>"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              value: "<smtp-user>"
            - name: SMTP_PASS
              value: "<smtp-pass>"
            - name: EMAIL_FROM
              value: "<from-email>"
