apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "false"
        sidecar.opentelemetry.io/inject: "false"
    spec:
      containers:
        - name: customer-service
          image: 502612814580.dkr.ecr.us-east-1.amazonaws.com/customer-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: OTEL_SDK_DISABLED
              value: "true"
            - name: DB_HOST
              value: "bookstore-db-dev.cluster-cbkwtui28fxb.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              value: "customers_db"
            - name: DB_AUTO_INIT
              value: "true"
            - name: DB_TRUNCATE_ON_START
              value: "false"
            - name: ANDREW_ID
              value: "irish2"
            - name: KAFKA_BROKERS
              value: "98.88.99.206:9092,34.195.107.7:9092,54.221.160.63:9092"
            - name: KAFKA_TOPIC
              value: "irish2.customer.evt"
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: bookstore-ns
spec:
  type: ClusterIP
  selector:
    app: customer-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
